### ISSUE TITLE
Features Tracking Issue

### ISSUE THREAD

**Issue by severen** [SShrike/tutil#1]
This issue is for tracking the status of planned features that are to be implemented.
- [ ] #2 Implement terminal output paging.
- [ ] #3 Implement terminal ASCII and Unicode tables.
- [ ] #4 Implement system detection utilities.
- [ ] #5 Implement command detection utilities.
- [ ] #6 Implement text manipulation.
- [ ] #7 Implement terminal progress bars.
- [ ] #8 Implement terminal spinners.
- [ ] #9 Implement user input prompts.
- [ ] #10 Support Windows.
